server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/
        - id: userprofile-route
          uri: lb://userprofile
          predicates:
            - Path=/userprofile/**
        - id: chat-app-route
          uri: lb://chat-app
          predicates:
            - Path=/chat/**
        - id: posts-route
          uri: lb://posts
          predicates:
            - Path=/posts/**
        - id: eureka-route
          uri: lb://eserver
          predicates:
            - Path=/eserver/**
        - id: frontend-route
          uri: http://frontend.collreach:8081
          predicates:
              - Path=/**
management:
  endpoints:
    web:
      exposure:
        include: "*"


#eureka:
#  client:
#    serviceURL:
#      defaultZone: http://eserver:8761/eureka/
