server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/
        - id: userprofile-route
          uri: http://userprofile.collreach:8082
          predicates:
            - Path=/userprofile/**
        - id: chat-app-route
          uri: http://chat-app.cr:8083
          predicates:
            - Path=/chat/**
        - id: posts-route
          uri: http://posts.collreach:8084
          predicates:
            - Path=/posts/**
#         - id: eureka-route
#           uri: lb://eserver
#           predicates:
#             - Path=/eserver/**
        - id: projects-route
          uri: http://projects.collreach:8086
          predicates:
            - Path=/api.projects/**
        - id: frontend-route
          uri: http://frontend.collreach:8081
          predicates:
              - Path=/**
management:
  endpoints:
    web:
      exposure:
        include: "*"


#eureka:
#  client:
#    serviceURL:
#      defaultZone: http://eserver:8761/eureka/
