server:
 port: 8086
 servlet:
   context-path: /projects

spring:
 application:
   name: projects
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate:
       format_sql: true
 datasource:
   url: jdbc:mysql://collreach-rds.cr:3306/collreach_userlogin?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
   username: collreach
   password: collreach
 servlet:
   multipart:
     max-file-size: 10MB
     max-request-size: 10MB
     enabled: true
